package com.tankecho.zensudoku.tests;
import android.app.*;import android.content.*;import android.os.*;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.time.*;
public class DemoV17 extends V17DeviceTests{
 File flag(String name){return new File(getTargetContext().getFilesDir(),name);}
 void mark(String name)throws Exception{flag(name).createNewFile();}
 void stamp(){TextView tag=new TextView(activity);tag.setText("功能演示 · 示例数据");tag.setTextSize(9);tag.setTextColor(0xff7c8792);tag.setPadding(0,4,20,0);tag.setGravity(Gravity.RIGHT);activity.addContentView(tag,new android.widget.FrameLayout.LayoutParams(-1,-2,Gravity.TOP));}
 void pause(long ms){SystemClock.sleep(ms);}
 @Override public void onStart(){Bundle out=new Bundle();try{
  activity=startActivitySync(new Intent().setClassName("com.tankecho.zensudoku","com.tankecho.zensudoku.MainActivity").addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TASK));
  ui(()->{Object store=field(activity,"store");JSONObject records=new JSONObject(),days=new JSONObject();for(int d=0;d<30;d++){if(d%4==1)continue;String date=LocalDate.now().minusDays(29-d).toString();long ms=(18*60-d*14)*1000L;String id="demo-"+d;JSONObject r=new JSONObject().put("id",id).put("date",date).put("endDate",date).put("status","won").put("level",0).put("ms",ms).put("hints",d%5==0?1:0).put("mistakes",d%3==0?1:0).put("daily",d%2==0?date:"");records.put(id,r);days.put(date,new JSONObject().put("ms",ms));}set(store,"records",records);set(store,"days",days);set(store,"motion",true);set(activity,"game",null);invoke("changeTheme",new Class[]{int.class},0);invoke("navigate",new Class[]{String.class},"home");stamp();});mark("v17-demo-ready");for(int i=0;i<200&&!flag("v17-demo-start").exists();i++)pause(100);pause(2200);shot("demo-home.png");
  ui(()->{stage(false);click("全盘候选数");stamp();});pause(1900);ui(()->{find(activity.getWindow().getDecorView(),"输入数字 5").performLongClick();});pause(1500);shot("demo-candidates.png");ui(()->click("使用提示"));pause(3200);shot("demo-hint.png");ui(()->hint().getButton(AlertDialog.BUTTON_POSITIVE).performClick());pause(900);
  ui(()->{invoke("navigate",new Class[]{String.class},"home");invoke("showDailyCalendar",new Class[]{YearMonth.class},YearMonth.now());});pause(2200);shot("demo-daily.png");ui(()->{((AlertDialog)field(activity,"calendarDialog")).dismiss();stage(true);set(game(),"mistakes",4);invoke("updateGame",new Class[]{});stamp();});pause(2000);shot("demo-practice.png");
  ui(()->{invoke("navigate",new Class[]{String.class},"profile");stamp();});pause(300);ui(()->{View title=findText(activity.getWindow().getDecorView(),"最近 30 天 · 同难度用时");ScrollView sc=(ScrollView)((View)field(activity,"content")).getParent();sc.scrollTo(0,((View)title.getParent()).getTop());stamp();});pause(2600);shot("demo-trend.png");ui(()->((ScrollView)((View)field(activity,"content")).getParent()).fullScroll(View.FOCUS_DOWN));pause(2200);shot("demo-settings.png");
  ui(()->{stage(false);int[] answer=values("solution").clone(),puzzle=answer.clone();puzzle[80]=0;Object g=game().getClass().getConstructor(int[].class,int[].class,int.class).newInstance(puzzle,answer,0);set(g,"elapsedMs",7*60000L);set(activity,"game",g);invoke("navigate",new Class[]{String.class},"game");stamp();select(80);click("输入数字 "+answer[80]);});pause(4500);shot("demo-record.png");pause(1800);mark("v17-demo-done");for(int i=0;i<300&&!flag("v17-demo-stop").exists();i++)pause(100);ui(()->activity.finish());out.putString("stream","DEMO_V17_SUCCESS guided hints, candidates, calendar, practice, trend, backup settings, personal record");finish(Activity.RESULT_OK,out);
 }catch(Throwable e){out.putString("stream","FAIL "+android.util.Log.getStackTraceString(e));finish(Activity.RESULT_CANCELED,out);}}
}
