package com.tankecho.zensudoku.tests;
import android.app.*;import android.content.*;import android.os.*;import android.graphics.*;import android.view.*;import android.widget.*;import java.io.*;import java.time.*;import java.util.*;import org.json.*;

/** Real production rendering, lifecycle and compatibility. Fixtures are test APK only. */
public class MedalDeviceTests extends V19DeviceTests {
    boolean systemOff;
    @Override public void onCreate(Bundle args){systemOff=args!=null&&"true".equals(args.getString("system_off"));super.onCreate(args);}
    void seedAll()throws Exception{Object store=field(activity,"store");JSONObject records=new JSONObject(),days=new JSONObject();for(int i=0;i<140;i++){String date=LocalDate.now().minusDays(i%40).toString(),id="medal-demo-"+i;boolean practice=i>=120;records.put(id,new JSONObject().put("id",id).put("date",date).put("endDate",date).put("status","won").put("level",i%4).put("hints",0).put("mistakes",0).put("practice",practice).put("daily",i<12?date:"").put("ms",600000));days.put(date,new JSONObject().put("ms",1800000));}set(store,"records",records);set(store,"days",days);set(store,"current","");set(activity,"game",null);}
    void gallery(boolean all,boolean motion,int theme)throws Exception{Object store=field(activity,"store");if(all)seedAll();else{set(store,"records",new JSONObject());set(store,"days",new JSONObject());}set(store,"motion",motion);set(activity,"statsTab",1);invoke("changeTheme",new Class[]{int.class},theme);invoke("navigate",new Class[]{String.class},"stats");}
    View art(String id){return decor().findViewWithTag("medal-art:"+id);}
    View dialogArt(String id)throws Exception{return ((AlertDialog)field(activity,"medalDialog")).getWindow().getDecorView().findViewWithTag("medal-art:"+id);}
    void scrollTo(View target)throws Exception{ScrollView scroll=(ScrollView)((View)field(activity,"content")).getParent();Rect r=new Rect();target.getDrawingRect(r);scroll.offsetDescendantRectToMyCoords(target,r);scroll.scrollTo(0,Math.max(0,r.top-30));}
    void motion(View v,boolean on)throws Exception{java.lang.reflect.Method m=v.getClass().getDeclaredMethod("setMotionEnabled",boolean.class);m.setAccessible(true);m.invoke(v,on);}
    Bitmap renderArt(View v){Bitmap b=Bitmap.createBitmap(336,384,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(b);c.scale(336f/v.getWidth(),384f/v.getHeight());v.draw(c);return b;}
    long fingerprint(Bitmap b){long h=1125899906842597L;for(int y=0;y<b.getHeight();y+=2)for(int x=0;x<b.getWidth();x+=2)h=31*h+b.getPixel(x,y);return h;}
    @Override void shot(String name)throws Exception{Bitmap b=getUiAutomation().takeScreenshot();File folder=new File(getTargetContext().getFilesDir(),"v191-proof");folder.mkdirs();try(FileOutputStream out=new FileOutputStream(new File(folder,name+".png"))){b.compress(Bitmap.CompressFormat.PNG,100,out);}b.recycle();}
    void contact()throws Exception{Bitmap sheet=Bitmap.createBitmap(1344,1648,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(sheet);c.drawColor(0xfff3f5f8);Paint text=new Paint(3);text.setColor(0xff263344);text.setTextSize(19);text.setTextAlign(Paint.Align.CENTER);List<View> arts=new ArrayList<>();collect(decor(),arts);Set<Long> hashes=new HashSet<>();int n=0;for(View v:arts){Bitmap b=renderArt(v);hashes.add(fingerprint(b));c.drawBitmap(b,(n%4)*336,(n/4)*412,text);Object medal=field(v,"medal");c.drawText((String)field(medal,"name"),(n%4)*336+168,(n/4)*412+403,text);b.recycle();n++;}ok(n==16&&hashes.size()==16,"all 16 compact production badges render distinct pixels with motion disabled");File folder=new File(getTargetContext().getFilesDir(),"v191-proof");folder.mkdirs();try(FileOutputStream out=new FileOutputStream(new File(folder,"medal-collection.png"))){sheet.compress(Bitmap.CompressFormat.PNG,100,out);}sheet.recycle();}
    void collect(View v,List<View> arts){if(v.getClass().getSimpleName().equals("MedalView"))arts.add(v);if(v instanceof ViewGroup)for(int i=0;i<((ViewGroup)v).getChildCount();i++)collect(((ViewGroup)v).getChildAt(i),arts);}
    @Override public void onStart(){Bundle out=new Bundle();try{
        getUiAutomation();activity=startActivitySync(new Intent().setClassName("com.tankecho.zensudoku","com.tankecho.zensudoku.MainActivity").addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TASK));
        if(systemOff){ui(()->gallery(true,true,0));SystemClock.sleep(350);ui(()->{ok(!android.animation.ValueAnimator.areAnimatorsEnabled(),"system animators actually disabled");scrollTo(art("journey-1"));});SystemClock.sleep(250);ui(()->{List<View> list=new ArrayList<>();collect(decor(),list);for(View v:list)ok(field(v,"animator")==null,"system-off static medal "+v.getTag());choose("奖章 百次回响");});SystemClock.sleep(300);ui(()->{ok(field(dialogArt("journey-100"),"animator")==null,"system-off royal detail remains still");activity.finish();});out.putString("stream",log+"PASS "+checks+" system motion-off checks\n");finish(Activity.RESULT_OK,out);return;}
        ui(()->gallery(true,false,0));SystemClock.sleep(500);ui(()->{contact();List<View> arts=new ArrayList<>();collect(decor(),arts);for(View v:arts)ok(field(v,"animator")==null,"motion preference yields static badge "+v.getTag());scrollTo(art("journey-1"));});shot("journey-static");
        ui(()->{set(field(activity,"store"),"motion",true);invoke("setEchoMotion",new Class[]{View.class,boolean.class},(View)field(activity,"root"),true);scrollTo(art("journey-1"));});SystemClock.sleep(300);
        final View[] off={null},detail={null};ui(()->{ok(field(art("journey-1"),"animator")!=null,"visible earned badge animates");ok(field(art("focus-ten-hours"),"animator")==null,"offscreen badge has no animator");off[0]=art("journey-1");scrollTo(art("focus-ten-hours"));});SystemClock.sleep(250);
        ui(()->{ok(field(off[0],"animator")==null,"scrolling fully offscreen stops animator");ok(field(art("focus-ten-hours"),"animator")!=null,"newly visible high badge starts");choose("奖章 时间的朋友");});SystemClock.sleep(350);
        final long[] a={0};ui(()->{detail[0]=dialogArt("focus-ten-hours");ok(field(detail[0],"animator")!=null,"earned high-tier detail animates");ok(field(art("focus-ten-hours"),"animator")==null,"gallery behind modal stops animating");Bitmap b=renderArt(detail[0]);a[0]=fingerprint(b);b.recycle();});SystemClock.sleep(800);
        ui(()->{Bitmap b=renderArt(detail[0]);ok(fingerprint(b)!=a[0],"high-tier frame actually changes across time");b.recycle();callActivityOnPause(activity);ok(field(detail[0],"animator")==null,"background immediately stops dialog finish");callActivityOnResume(activity);});SystemClock.sleep(150);
        ui(()->{ok(field(detail[0],"animator")!=null,"foreground resumes detail finish");motion(detail[0],false);Bitmap b=renderArt(detail[0]);a[0]=fingerprint(b);b.recycle();});SystemClock.sleep(200);
        ui(()->{Bitmap b=renderArt(detail[0]);ok(fingerprint(b)==a[0]&&field(detail[0],"animator")==null,"motion-off detail remains pixel-stable");b.recycle();((AlertDialog)field(activity,"medalDialog")).dismiss();ok(field(detail[0],"animator")==null,"dismissed detail releases animator");});
        ui(()->{gallery(false,true,1);scrollTo(art("journey-1"));choose("奖章 初次相遇");});SystemClock.sleep(300);ui(()->{ok(field(dialogArt("journey-1"),"animator")==null,"locked badge has no earned animation");ok(findText(((AlertDialog)field(activity,"medalDialog")).getWindow().getDecorView(),"0 / 1 局")!=null,"locked condition/progress preserved");});shot("locked-dark");
        ui(()->{((AlertDialog)field(activity,"medalDialog")).dismiss();gallery(true,true,1);});SystemClock.sleep(500);ui(()->scrollTo(art("insight-independent")));SystemClock.sleep(250);shot("insight-dark");
        ui(()->{View old=art("insight-perfect");invoke("navigate",new Class[]{String.class},"home");ok(field(old,"animator")==null&&!old.isAttachedToWindow(),"navigation releases medal animators");invoke("start",new Class[]{int.class,boolean.class},0,false);Object store=field(activity,"store");String backup=(String)store.getClass().getMethod("exportBackup").invoke(store);JSONObject valid=(JSONObject)store.getClass().getMethod("validateBackup",String.class).invoke(null,backup);ok(valid.getJSONObject("records").length()>=140,"visual changes retain imported record schema");activity.finish();});
        out.putString("stream",log+"PASS "+checks+" medal rendering and lifecycle checks\n");finish(Activity.RESULT_OK,out);
    }catch(Throwable e){out.putString("stream",log+"FAIL "+android.util.Log.getStackTraceString(e));finish(Activity.RESULT_CANCELED,out);}}
}
