package com.tankecho.zensudoku.tests;
import android.app.*;import android.content.*;import android.os.*;import org.json.*;import java.io.*;import java.nio.file.*;import java.util.*;
public class PersistenceV17 extends V17DeviceTests{
 private String phase;
 @Override public void onCreate(Bundle b){phase=b.getString("phase","read");super.onCreate(b);}
 @Override public void onStart(){Bundle out=new Bundle();try{activity=startActivitySync(new Intent().setClassName("com.tankecho.zensudoku","com.tankecho.zensudoku.MainActivity").addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TASK));File expected=new File(getTargetContext().getFilesDir(),"v17-persistence.json");
 if(phase.equals("write")){ui(()->{stage(false);int at=empty();select(at);click("笔记");click("输入数字 2");click("笔记");click("输入数字 "+values("solution")[at]);click("使用提示");hint().dismiss();invoke("navigate",new Class[]{String.class},"home");JSONObject o=new JSONObject().put("board",Arrays.toString(values("board"))).put("notes",Arrays.toString(values("notes"))).put("hints",integer("hints")).put("hintCell",integer("pendingHintCell"));Files.write(expected.toPath(),o.toString().getBytes("UTF-8"));});Class.forName("com.tankecho.zensudoku.Store").getMethod("awaitWrites").invoke(null);ok(expected.exists(),"process recovery fixture saved");}
 else{JSONObject o=new JSONObject(new String(Files.readAllBytes(expected.toPath()),"UTF-8"));ui(()->{ok(o.getString("board").equals(Arrays.toString(values("board"))),"board persists after process exit");ok(o.getString("notes").equals(Arrays.toString(values("notes"))),"notes persist after process exit");ok(integer("hints")==o.getInt("hints")&&integer("pendingHintCell")==o.getInt("hintCell"),"pending hint and budget persist after process exit");ok((Boolean)call(game(),"canUndo",new Class[]{}),"undo persists after process exit");invoke("navigate",new Class[]{String.class},"game");click("使用提示");ok(integer("hints")==o.getInt("hints"),"recovered explanation does not charge twice");hint().dismiss();});ui(()->{int filled=(Integer)call(game(),"filled",new Class[]{});click("撤销");ok((Integer)call(game(),"filled",new Class[]{})==filled-1,"recovered undo restores previous board");int at=integer("selected");boolean any=false;for(int m:values("notes"))any|=m!=0;ok(any,"recovered undo restores earlier pencil notes");});}
 ui(()->activity.finish());Class.forName("com.tankecho.zensudoku.Store").getMethod("awaitWrites").invoke(null);out.putString("stream",log+"PERSISTENCE_V17_SUCCESS "+phase+" "+checks);finish(Activity.RESULT_OK,out);
 }catch(Throwable e){out.putString("stream",log+"FAIL "+android.util.Log.getStackTraceString(e));finish(Activity.RESULT_CANCELED,out);}}
}
