package com.tankecho.zensudoku.tests;
import android.app.*;import android.content.*;import android.os.*;import android.view.accessibility.*;import java.util.*;
/** Exercises the actual system document picker and application activity-result callbacks. */
public class SafV17 extends V17DeviceTests {
 AccessibilityNodeInfo byText(AccessibilityNodeInfo n,String text){if(n==null)return null;if(n.getText()!=null&&text.equalsIgnoreCase(n.getText().toString()))return n;for(int i=0;i<n.getChildCount();i++){AccessibilityNodeInfo f=byText(n.getChild(i),text);if(f!=null)return f;}return null;}
 AccessibilityNodeInfo editor(AccessibilityNodeInfo n){if(n==null)return null;if("android.widget.EditText".contentEquals(n.getClassName()))return n;for(int i=0;i<n.getChildCount();i++){AccessibilityNodeInfo f=editor(n.getChild(i));if(f!=null)return f;}return null;}
 void tap(String...texts)throws Exception{for(int retry=0;retry<70;retry++){AccessibilityNodeInfo root=getUiAutomation().getRootInActiveWindow();for(String text:texts){AccessibilityNodeInfo node=byText(root,text);while(node!=null){if(node.isClickable()&&node.performAction(AccessibilityNodeInfo.ACTION_CLICK))return;node=node.getParent();}}SystemClock.sleep(150);}throw new AssertionError("No clickable "+Arrays.toString(texts));}
 AccessibilityNodeInfo picker()throws Exception{for(int i=0;i<100;i++){AccessibilityNodeInfo n=getUiAutomation().getRootInActiveWindow();if(n!=null&&n.getPackageName()!=null&&n.getPackageName().toString().contains("documentsui"))return n;SystemClock.sleep(100);}return null;}
 void idleIO()throws Exception{for(int i=0;i<100;i++){if(!(Boolean)field(activity,"ioBusy"))return;SystemClock.sleep(100);}throw new AssertionError("IO timed out");}
 void tree(AccessibilityNodeInfo n){if(n==null)return;if(n.getText()!=null)log.append(n.getClassName()).append(' ').append(n.getText()).append('\n');for(int i=0;i<n.getChildCount();i++)tree(n.getChild(i));}
 @Override public void onStart(){Bundle result=new Bundle();try{
  activity=startActivitySync(new Intent().setClassName("com.tankecho.zensudoku","com.tankecho.zensudoku.MainActivity").addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TASK));final int[][] expected={null};final String name="EchoSodu-QA-"+System.currentTimeMillis()+".json";
  ui(()->{stage(false);int at=empty();select(at);click("输入数字 "+values("solution")[at]);expected[0]=values("board").clone();invoke("navigate",new Class[]{String.class},"profile");invoke("pickBackup",new Class[]{boolean.class},true);});SystemClock.sleep(800);
  AccessibilityNodeInfo root=picker();ok(root!=null&&root.getPackageName().toString().contains("documentsui"),"export opens Android document picker");AccessibilityNodeInfo edit=editor(root);ok(edit!=null,"export filename editable");Bundle text=new Bundle();text.putCharSequence(AccessibilityNodeInfo.ACTION_ARGUMENT_SET_TEXT_CHARSEQUENCE,name);edit.performAction(AccessibilityNodeInfo.ACTION_SET_TEXT,text);tap("Save","保存");SystemClock.sleep(1000);idleIO();
  ui(()->{ok(!(Boolean)field(activity,"ioBusy"),"export callback completes");stage(true);invoke("navigate",new Class[]{String.class},"profile");invoke("pickBackup",new Class[]{boolean.class},false);});SystemClock.sleep(700);ok(picker()!=null,"import opens Android document picker");tap(name);SystemClock.sleep(700);tap("取消","Cancel");ui(()->ok((Boolean)field(game(),"practice"),"cancel import leaves active game unchanged"));
  ui(()->invoke("pickBackup",new Class[]{boolean.class},false));SystemClock.sleep(600);tap(name);SystemClock.sleep(700);shot("backup-confirmation.png");tap("确认导入");SystemClock.sleep(700);idleIO();
  ui(()->{ok(Arrays.equals(expected[0],values("board"))&&!(Boolean)field(game(),"practice"),"actual file import restores exported board and mode");ok((Boolean)call(game(),"canUndo",new Class[]{}),"actual file import restores undo");ok((Boolean)call(field(activity,"store"),"hasRecovery",new Class[]{}),"actual import retains previous local state for recovery");activity.finish();});
  Class.forName("com.tankecho.zensudoku.Store").getMethod("awaitWrites").invoke(null);result.putString("stream",log+"SAF_V17_SUCCESS "+checks+" file="+name);finish(Activity.RESULT_OK,result);
 }catch(Throwable e){tree(getUiAutomation().getRootInActiveWindow());result.putString("stream",log+"FAIL "+android.util.Log.getStackTraceString(e));finish(Activity.RESULT_CANCELED,result);}}
}
