package com.tankecho.zensudoku.tests;
import android.app.*;import android.content.*;import android.os.*;import android.graphics.*;import android.view.*;import android.widget.*;import java.io.*;import org.json.*;

public class TutorialDeviceTests extends V19DeviceTests {
    Object sandbox()throws Exception{return field(activity,"sandbox");}
    int[] cells()throws Exception{return (int[])field(sandbox(),"board");}
    void lesson(int n)throws Exception{invoke("openLesson",new Class[]{int.class},n);}
    void cell(int n)throws Exception{((ViewGroup)field(activity,"board")).getChildAt(n).performClick();}
    void key(int n){choose("教学数字 "+n);}
    void assertFooter(){View v=find(decor(),"教学下一节");Rect r=new Rect();ok(v!=null&&v.getGlobalVisibleRect(r)&&r.height()>=v.getHeight()-1,"next button fully visible without scrolling");}
    void capture(String name)throws Exception{SystemClock.sleep(350);Bitmap b=getUiAutomation().takeScreenshot();File folder=new File(getTargetContext().getFilesDir(),"v110-proof");folder.mkdirs();try(FileOutputStream out=new FileOutputStream(new File(folder,name+".png"))){b.compress(Bitmap.CompressFormat.PNG,100,out);}b.recycle();}
    void focus(){for(int i=0;i<50&&!activity.hasWindowFocus();i++)SystemClock.sleep(60);}
    Activity help(Activity main)throws Exception{activity=main;ActivityMonitor monitor=addMonitor("com.tankecho.zensudoku.TutorialActivity",null,false);ui(()->invoke("help",new Class[]{}));Activity tutorial=monitor.waitForActivityWithTimeout(5000);removeMonitor(monitor);ok(tutorial!=null,"existing help opens learning activity");activity=tutorial;focus();return tutorial;}
    String payload(Object store)throws Exception{return new JSONObject((String)store.getClass().getMethod("exportBackup").invoke(store)).getString("payload");}
    @Override public void onStart(){Bundle out=new Bundle();try{
        getUiAutomation();Activity main=startActivitySync(new Intent().setClassName("com.tankecho.zensudoku","com.tankecho.zensudoku.MainActivity").addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TASK));activity=main;
        ui(()->{invoke("start",new Class[]{int.class,boolean.class},0,false);set(main,"paused",true);});help(main);
        Object store=field(main,"store"),real=field(main,"game");String before=payload(store),realBoard=(String)real.getClass().getMethod("encode",int[].class).invoke(null,field(real,"board"));long elapsed=(Long)field(real,"elapsedMs");
        ui(()->ok(count(decor(),"学习 ")==6,"six accessible topics"));capture("learn-overview");
        ui(()->{choose("学习 数独的三个规则");choose("观察行");choose("观察列");choose("观察宫");ok(((Integer)field(activity,"completed")&1)!=0,"three regions complete rule lesson");});SystemClock.sleep(350);ui(()->assertFooter());
        ui(()->{lesson(1);key(4);ok(cells()[2]==0,"cell-first requires a selection");cell(2);key(3);ok(cells()[2]==0&&(Integer)field(sandbox(),"mistakes")==1,"wrong tutorial answer remains empty");key(4);ok(cells()[2]==4,"cell-first input fills real board");ok(((Integer)field(activity,"completed")&2)!=0,"classic lesson completed");Object timeline=field(field(activity,"board"),"timeline");for(Object event:(java.util.List<?>)timeline.getClass().getMethod("active",long.class).invoke(timeline,SystemClock.uptimeMillis()))ok((Integer)field(event,"kind")!=5,"corrected answer clears old wrong-digit overlay");});capture("learn-classic");
        ui(()->{lesson(2);key(5);ok((Integer)field(sandbox(),"activeNumber")==5,"quick mode selects five");for(int at:new int[]{0,14,24})cell(at);ok((Integer)field(sandbox(),"activeNumber")==0,"last five deselects active key");ok(!find(decor(),"教学数字 5").isEnabled(),"completed five key disabled");cell(0);ok((Integer)field(sandbox(),"selected")==0,"completed board five remains selectable");ok(((Integer)field(activity,"completed")&4)!=0,"quick lesson completed");});capture("learn-quick");
        ui(()->{lesson(3);cell(2);choose("教学候选数");ok(((boolean[])field(sandbox(),"candidates"))[2],"automatic candidate toggles on");choose("教学笔记");key(4);ok(cells()[2]==0&&((int[])field(sandbox(),"notes"))[2]==8,"manual note stays a note");ok((Integer)field(sandbox(),"mistakes")==0,"notes do not use mistake budget");ok(((Integer)field(activity,"completed")&8)!=0,"candidate and note lesson complete");});capture("learn-notes");
        ui(()->{lesson(4);ok(!find(decor(),"教学填入提示").isEnabled(),"hint apply disabled before explanation");cell(2);choose("教学查看提示");ok((Integer)field(sandbox(),"hints")==1&&cells()[2]==0,"viewing explanation costs one before fill");choose("教学查看提示");ok((Integer)field(sandbox(),"hints")==1,"rereading same hint never double charges");ok(((String)field(sandbox(),"pendingHintReason")).contains("只剩"),"actual logical explanation shown");});capture("learn-hint");
        ui(()->{choose("教学填入提示");ok(cells()[2]==4&&((boolean[])field(sandbox(),"hinted"))[2],"explicit apply fills and locks hint cell");ok(((Integer)field(activity,"completed")&16)!=0,"hint lesson complete");lesson(5);cell(2);key(4);ok(field(sandbox(),"status").equals("won"),"real sandbox reaches victory");ok(((Integer)field(activity,"completed")&32)!=0,"victory lesson complete");ok(field(activity,"confetti")!=null,"celebration is actual native overlay");});SystemClock.sleep(700);capture("learn-victory");
        ui(()->{lesson(1);invoke("showDemo",new Class[]{});ok((Boolean)field(activity,"demonstrating"),"demo starts");cell(2);ok(!(Boolean)field(activity,"demonstrating"),"manual tap cancels demo callbacks");});SystemClock.sleep(2100);ui(()->ok(cells()[2]==0,"cancelled demonstration cannot fill later"));
        ui(()->{invoke("showDemo",new Class[]{});callActivityOnPause(activity);ok(!(Boolean)field(activity,"demonstrating")&&field(activity,"confetti")==null,"background stops demo and effects");callActivityOnResume(activity);});SystemClock.sleep(2200);ui(()->ok(cells()[2]==0,"foreground does not autoplay stale script"));
        ui(()->{lesson(3);cell(2);choose("教学笔记");key(4);});ActivityMonitor recreate=addMonitor("com.tankecho.zensudoku.TutorialActivity",null,false);ui(()->activity.recreate());Activity restored=recreate.waitForActivityWithTimeout(5000);removeMonitor(recreate);ok(restored!=null,"tutorial actually recreated");activity=restored;focus();
        ui(()->{ok((Integer)field(activity,"lesson")==3&&((int[])field(sandbox(),"notes"))[2]==8,"recreation restores lesson and handwritten notes");ok((Integer)field(activity,"completed")==63,"recreation retains completed topics");assertFooter();set(activity,"motion",false);lesson(5);cell(2);key(4);ok(field(activity,"confetti")==null,"motion preference prevents full-screen effects");ok(!(Boolean)((Object)field(activity,"board")).getClass().getMethod("isVictoryRunning").invoke(field(activity,"board")),"motion off prevents board wave");});
        ok(payload(store).equals(before),"all lessons and recreation leave real saved data unchanged");ok((Long)field(real,"elapsedMs")==elapsed,"real paused game timer unchanged while learning");
        ui(()->{activity.finish();});activity=main;focus();ui(()->{ok((Boolean)field(main,"paused"),"return preserves original paused state");ok(field(main,"game")==real,"return keeps original game object");ok(realBoard.equals(real.getClass().getMethod("encode",int[].class).invoke(null,field(real,"board"))),"original board untouched");invoke("navigate",new Class[]{String.class},"settings");ok(find(decor(),"项目 GitHub").isEnabled(),"repository link enabled");ok(find(decor(),"GitHub 版本下载")!=null&&find(decor(),"GitHub 反馈问题")!=null,"release and issue links present");});
        IntentFilter filter=new IntentFilter(Intent.ACTION_VIEW);filter.addDataScheme("https");ActivityMonitor links=addMonitor(filter,new ActivityResult(Activity.RESULT_OK,null),true);ui(()->{choose("项目 GitHub");choose("GitHub 版本下载");choose("GitHub 反馈问题");});ok(links.getHits()==3,"all three GitHub actions issue browser intents");removeMonitor(links);
        ui(()->{invoke("changeTheme",new Class[]{int.class},1);});help(main);ui(()->{ok((Boolean)field(field(activity,"palette"),"dark"),"tutorial inherits dark theme");lesson(4);cell(2);choose("教学查看提示");});SystemClock.sleep(350);ui(()->assertFooter());capture("learn-dark");
        ui(()->activity.finish());activity=main;focus();ui(()->{invoke("navigate",new Class[]{String.class},"game");set(main,"paused",false);});help(main);long runningBefore=(Long)field(field(main,"game"),"elapsedMs");SystemClock.sleep(600);ok((Long)field(field(main,"game"),"elapsedMs")==runningBefore,"previously running game stops timer in tutorial");ui(()->activity.finish());activity=main;focus();SystemClock.sleep(600);ui(()->{ok(!(Boolean)field(main,"paused")&&(Long)field(field(main,"game"),"elapsedMs")>runningBefore,"previously running game resumes clock on return");main.finish();});out.putString("stream",log+"PASS "+checks+" tutorial device checks\n");finish(Activity.RESULT_OK,out);
    }catch(Throwable e){out.putString("stream",log+"FAIL "+android.util.Log.getStackTraceString(e));finish(Activity.RESULT_CANCELED,out);}}
}
