import com.tankecho.zensudoku.*;import java.util.*;import java.nio.file.*;
public class V17CoreTest{
 static int checks;static void ok(boolean b,String name){checks++;if(!b)throw new AssertionError(name);}
 public static void main(String[] args)throws Exception{int count=0;for(String line:Files.readAllLines(Paths.get(args[0]))){String[] parts=line.split("\\t");int level=Integer.parseInt(parts[0]);int[] puzzle=Game.digits(parts[1]),solution=Game.digits(parts[2]);ok(Game.countSolutions(puzzle.clone(),2)==1,"unique");ok(HintEngine.grade(puzzle)==level,"technique grade");Game g=new Game(puzzle,solution,level);int rounds=0;while(g.filled()<81){HintEngine.Plan hint=HintEngine.find(g.board,-1);ok(hint!=null,"logical continuation");ok(hint.digit==solution[hint.cell],"deduction agrees with independent answer");ok(hint.explanation.length()>10&&hint.related.length>0,"explanation evidence");g.selected=hint.cell;g.enter(hint.digit);ok(++rounds<=81,"terminates");}ok(g.status.equals("won"),"solves");count++;}
 int[] solution=Game.digits("534678912672195348198342567859761423426853791713924856961537284287419635345286179"),puzzle=solution.clone();puzzle[0]=puzzle[1]=0;Game g=new Game(puzzle,solution,0);g.practice=true;g.selected=0;for(int i=0;i<8;i++)g.enter(1);ok(g.mistakes==8&&g.status.equals("playing"),"practice unlimited errors");Game challenge=new Game(puzzle,solution,0);challenge.selected=0;for(int i=0;i<3;i++)challenge.enter(1);ok(challenge.status.equals("lost"),"challenge three errors");
 HintEngine.Plan plan=HintEngine.find(g.board,0);ok(g.reserveHint(plan)&&g.hints==1&&g.board[plan.cell]==0,"hint reveal counts without filling");ok(g.applyPendingHint()&&g.hints==1&&g.board[plan.cell]==plan.digit,"hint fill no double charge");ok(!g.undo(),"hint cannot be undone");g.selected=1;g.enter(solution[1]);ok(g.status.equals("won"),"practice completes");
 Game candidates=new Game(puzzle,solution,0);candidates.toggleAllCandidates();ok(candidates.showCandidates(0)&&candidates.showCandidates(1),"all candidates");candidates.selected=0;candidates.toggleCandidates();ok(!candidates.showCandidates(0)&&candidates.showCandidates(1),"per cell hide from all");candidates.quickMode=true;candidates.selectNumber(3);candidates.inspect(5);int before=candidates.filled();candidates.selectCell(0);ok(before==candidates.filled()&&candidates.highlightNumber()==5,"inspect never fast-fills");candidates.inspect(5);ok(candidates.inspectNumber==0,"inspect toggles off");candidates.selected=0;candidates.enter(5);ok(candidates.canUndo(),"undo available");Game restored=new Game(puzzle,solution,0);restored.board=candidates.board.clone();restored.restoreUndo(candidates.undoSnapshots());ok(restored.undo()&&restored.board[0]==0,"undo snapshots survive reconstruction");
 System.out.println("PASS "+checks+" v17 core checks over "+count+" puzzles");}
}
