package com.tankecho.zensudoku.tests;
import android.app.*;import android.content.*;import android.os.*;import android.view.*;import android.widget.*;import android.graphics.*;import org.json.*;import java.util.*;import java.lang.reflect.*;import java.io.*;
public class V17DeviceTests extends DeviceTests{
 void set(Object o,String n,Object v)throws Exception{Field f=o.getClass().getDeclaredField(n);f.setAccessible(true);f.set(o,v);}
 Object call(Object o,String name,Class<?>[] types,Object...args)throws Exception{return o.getClass().getMethod(name,types).invoke(o,args);}
 void stage(boolean practice)throws Exception{invoke("startGame",new Class[]{int.class,String.class,boolean.class},0,"",practice);set(game(),"quickMode",false);invoke("updateGame",new Class[]{});}
 AlertDialog hint()throws Exception{return (AlertDialog)field(activity,"hintDialog");}
 void shot(String name)throws Exception{SystemClock.sleep(200);Bitmap bitmap=getUiAutomation().takeScreenshot();File dir=new File(getTargetContext().getFilesDir(),"v17-proof");dir.mkdirs();try(FileOutputStream out=new FileOutputStream(new File(dir,name))){bitmap.compress(Bitmap.CompressFormat.PNG,100,out);}bitmap.recycle();}
 @Override public void onStart(){Bundle out=new Bundle();try{
  Intent launch=new Intent().setClassName("com.tankecho.zensudoku","com.tankecho.zensudoku.MainActivity").addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TASK);activity=startActivitySync(launch);waitForIdleSync();
  ui(()->{stage(false);click("全盘候选数");ok((Boolean)field(game(),"allCandidates"),"all candidates visible");int i=empty();select(i);click("候选数");ok(!(Boolean)game().getClass().getMethod("showCandidates",int.class).invoke(game(),i),"per-cell candidate can hide while all were visible");View n=find(activity.getWindow().getDecorView(),"输入数字 5");n.performLongClick();int before=(Integer)call(game(),"filled",new Class[]{});select(i);ok(integer("inspectNumber")==5&&before==(Integer)call(game(),"filled",new Class[]{}),"long press candidate inspect never fills");n.performLongClick();ok(integer("inspectNumber")==0,"candidate inspect cancels");
   stage(false);click("使用提示");ok(integer("hints")==1&&integer("pendingHintCell")>=0,"explanation consumes one hint before filling");ok(values("board")[integer("pendingHintCell")]==0&&hint().isShowing(),"explanation opens without placing answer");ok((Boolean)field(activity,"paused"),"reading hint pauses timer");});shot("guided-hint.png");
  final int[] hintedAt={0};ui(()->{hint().getButton(AlertDialog.BUTTON_NEGATIVE).performClick();});ui(()->{ok(!(Boolean)field(activity,"paused"),"closing hint resumes timer");click("使用提示");ok(integer("hints")==1,"reopening same explanation costs no extra hint");hintedAt[0]=integer("pendingHintCell");hint().getButton(AlertDialog.BUTTON_POSITIVE).performClick();});
  ui(()->{ok(values("board")[hintedAt[0]]==values("solution")[hintedAt[0]]&&integer("hints")==1,"actual fill button applies hint once");ok(!(Boolean)call(game(),"canUndo",new Class[]{}),"hint cannot be undone");stage(true);int i=empty();select(i);for(int k=0;k<5;k++)click("输入数字 "+(values("solution")[i]%9+1));ok(integer("mistakes")==5&&status().equals("playing"),"relaxed practice survives five mistakes");stage(false);i=empty();select(i);for(int k=0;k<3;k++)click("输入数字 "+(values("solution")[i]%9+1));ok(status().equals("lost"),"challenge still fails on third error");stage(false);int at=empty();select(at);click("输入数字 "+values("solution")[at]);ok((Boolean)call(game(),"canUndo",new Class[]{}),"entered move has undo");invoke("navigate",new Class[]{String.class},"home");});
  Class<?> storeClass=Class.forName("com.tankecho.zensudoku.Store");storeClass.getMethod("awaitWrites").invoke(null);ui(()->activity.finish());activity=startActivitySync(launch);waitForIdleSync();ui(()->{ok((Boolean)call(game(),"canUndo",new Class[]{}),"undo remains after activity recreation");invoke("navigate",new Class[]{String.class},"game");int filled=(Integer)call(game(),"filled",new Class[]{});click("撤销");ok((Integer)call(game(),"filled",new Class[]{})==filled-1,"restored undo changes the actual board");});
  final String[] backup={null};ui(()->{backup[0]=(String)call(field(activity,"store"),"exportBackup",new Class[]{});});JSONObject validated=(JSONObject)storeClass.getMethod("validateBackup",String.class).invoke(null,backup[0]);ok(validated.has("records")&&validated.has("current"),"exported save passes integrity and semantic checks");
  boolean rejected=false;try{storeClass.getMethod("validateBackup",String.class).invoke(null,backup[0].replace("\"version\": 1","\"version\": 999"));}catch(Exception e){rejected=true;}ok(rejected,"future backup version rejected");JSONObject damaged=new JSONObject(backup[0]);damaged.put("payload",damaged.getString("payload")+" ");rejected=false;try{storeClass.getMethod("validateBackup",String.class).invoke(null,damaged.toString());}catch(Exception e){rejected=true;}ok(rejected,"damaged backup rejected before restore");
  Object actualStore=field(activity,"store");final Object[] testStore={null};final String name="v17-backup-"+System.nanoTime();Context sandbox=new ContextWrapper(getTargetContext()){@Override public android.content.SharedPreferences getSharedPreferences(String ignored,int mode){return getBaseContext().getSharedPreferences(name,mode);}};
  ui(()->{testStore[0]=storeClass.getConstructor(Context.class).newInstance(sandbox);call(testStore[0],"importBackup",new Class[]{JSONObject.class},validated);ok((Boolean)call(testStore[0],"hasRecovery",new Class[]{}),"import retains a recovery point");Object restored=call(testStore[0],"load",new Class[]{});ok(Arrays.equals((int[])field(restored,"board"),values("board")),"backup restores exact board");ok((Integer)field(restored,"hints")==integer("hints"),"backup restores budget");});storeClass.getMethod("awaitWrites").invoke(null);ok(sandbox.getSharedPreferences(name,0).getString("current","").length()>81,"background transaction is durable");
  final long[] mainDisk={0};ui(()->{StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder().detectDiskWrites().penaltyListener(Runnable::run,v->mainDisk[0]++).build());for(int i=0;i<30;i++)call(actualStore,"save",new Class[]{game().getClass()},game());StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder().permitAll().build());});storeClass.getMethod("awaitWrites").invoke(null);ok(mainDisk[0]==0,"saving does not write disk on UI thread");
  ui(()->{Object st=testStore[0];JSONObject records=new JSONObject();String today=java.time.LocalDate.now().toString();records.put("challenge",new JSONObject().put("id","challenge").put("level",0).put("date",today).put("endDate",today).put("status","won").put("ms",120000).put("hints",0).put("mistakes",0));records.put("practice",new JSONObject(records.getJSONObject("challenge").toString()).put("id","practice").put("practice",true).put("ms",1000));set(st,"records",records);ok((Integer)call(st,"wins",new Class[]{})==1&&(Integer)call(st,"practiceWins",new Class[]{})==1,"challenge and practice wins separate");ok((Integer)call(st,"cleanWins",new Class[]{boolean.class,boolean.class},true,true)==1,"perfect challenge wins exclude relaxed practice");long[] trend=(long[])call(st,"trend",new Class[]{int.class},0);ok(trend[29]==120000&&trend[28]==-1,"trend skips blank dates and excludes practice");ok((Long)call(st,"best",new Class[]{int.class,String.class},0,"")==120000L,"record ignores practice times");
   JSONArray pool=((JSONArray)field(activity,"bank")).getJSONArray(0);Set<Integer> picks=new HashSet<>();set(st,"seen",new JSONObject());for(int i=0;i<pool.length();i++)picks.add((Integer)call(st,"choosePuzzle",new Class[]{int.class,JSONArray.class,Random.class},0,pool,new Random(i)));ok(picks.size()==60,"free-play base puzzles do not repeat within pool");int next=(Integer)call(st,"choosePuzzle",new Class[]{int.class,JSONArray.class,Random.class},0,pool,new Random(7));ok(next>=0&&next<60,"exhausted pool becomes available again");
   String day=java.time.LocalDate.now().minusDays(3).toString();invoke("startGame",new Class[]{int.class,String.class,boolean.class},1,day,false);int[] first=values("givens").clone();invoke("startGame",new Class[]{int.class,String.class,boolean.class},1,day,false);ok(Arrays.equals(first,values("givens")),"catch-up puzzle is deterministic");ok(field(game(),"dailyDate").equals(day)&&!(Boolean)field(game(),"practice"),"catch-up uses challenge rules and selected puzzle date");invoke("navigate",new Class[]{String.class},"home");ok(find(activity.getWindow().getDecorView(),"每日挑战日历")!=null,"daily calendar entry available");invoke("navigate",new Class[]{String.class},"profile");ok(find(activity.getWindow().getDecorView(),"导出存档")!=null&&find(activity.getWindow().getDecorView(),"导入存档")!=null,"backup actions inside profile");ok(findText(activity.getWindow().getDecorView(),"Echo 的小收藏")!=null,"achievement collection present");activity.finish();});
  ui(()->{Class<?> chart=Class.forName("com.tankecho.zensudoku.MainActivity$TrendView");Constructor<?> ctor=chart.getDeclaredConstructor(activity.getClass(),Context.class,long[].class);ctor.setAccessible(true);for(int pattern=0;pattern<4;pattern++){long[] series=new long[30];Arrays.fill(series,-1);if(pattern==1)series[0]=120000;else if(pattern==2)Arrays.fill(series,120000);else if(pattern==3){series[0]=180000;series[1]=160000;series[29]=90000;}View graph=(View)ctor.newInstance(activity,activity,series);graph.layout(0,0,660,250);Bitmap pixels=Bitmap.createBitmap(660,250,Bitmap.Config.ARGB_8888);graph.draw(new Canvas(pixels));pixels.recycle();ok(true,"trend renders empty/first-day/continuous/gapped series "+pattern);}});
  out.putString("stream",log+"PASS "+checks+" v17 device checks\n");finish(Activity.RESULT_OK,out);
 }catch(Throwable e){out.putString("stream",log+"FAIL "+android.util.Log.getStackTraceString(e));finish(Activity.RESULT_CANCELED,out);}}
}
