package com.tankecho.zensudoku.tests;
import android.app.*;import android.content.*;import android.os.*;import android.graphics.*;import android.view.*;import android.widget.*;import java.io.*;import java.time.*;import java.util.*;import org.json.*;

/** UI navigation and persistence in the real release; synthetic records are test-only. */
public class V19DeviceTests extends V18DeviceTests {
    View decor(){return activity.getWindow().getDecorView();}
    View prefix(View v,String label){if(v.getContentDescription()!=null&&v.getContentDescription().toString().startsWith(label))return v;if(v instanceof ViewGroup)for(int i=0;i<((ViewGroup)v).getChildCount();i++){View match=prefix(((ViewGroup)v).getChildAt(i),label);if(match!=null)return match;}return null;}
    int count(View v,String label){int n=v.getContentDescription()!=null&&v.getContentDescription().toString().startsWith(label)?1:0;if(v instanceof ViewGroup)for(int i=0;i<((ViewGroup)v).getChildCount();i++)n+=count(((ViewGroup)v).getChildAt(i),label);return n;}
    void choose(String label){View v=prefix(decor(),label);if(v==null)throw new AssertionError("Missing "+label);v.performClick();}
    void shot(String name)throws Exception{Bitmap b=getUiAutomation().takeScreenshot();File folder=new File(getTargetContext().getFilesDir(),"v19-proof");folder.mkdirs();try(FileOutputStream out=new FileOutputStream(new File(folder,name+".png"))){b.compress(Bitmap.CompressFormat.PNG,100,out);}b.recycle();}
    void seedRecords()throws Exception{Object store=field(activity,"store");JSONObject records=new JSONObject(),days=new JSONObject();for(int i=0;i<32;i++){String date=LocalDate.now().minusDays(i/2).toString(),id="demo-"+i;boolean practice=i%5==0;records.put(id,new JSONObject().put("id",id).put("date",date).put("endDate",date).put("status",i%7==0?"lost":"won").put("level",i%4).put("hints",i%3==0?0:1).put("mistakes",i%7==0?3:0).put("practice",practice).put("daily",i%4==0&&!practice?date:"").put("ms",(497+i*31)*1000L));JSONObject day=days.optJSONObject(date);if(day==null)day=new JSONObject().put("ms",0);day.put("ms",day.optLong("ms")+(497+i*31)*1000L);days.put(date,day);}set(store,"records",records);set(store,"days",days);}
    void stamp(){TextView label=new TextView(activity);label.setText("界面演示 · 示例统计数据");label.setTextColor(0xff84919e);label.setTextSize(9);label.setGravity(Gravity.RIGHT);label.setPadding(0,2,18,0);activity.addContentView(label,new FrameLayout.LayoutParams(-1,-2,Gravity.TOP));}
    @Override public void onStart(){Bundle out=new Bundle();try{
        getUiAutomation();Intent launch=new Intent().setClassName("com.tankecho.zensudoku","com.tankecho.zensudoku.MainActivity").addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TASK);activity=startActivitySync(launch);
        ui(()->{set(activity,"game",null);Object store=field(activity,"store");set(store,"current","");set(store,"quickMode",false);set(store,"records",new JSONObject());set(store,"days",new JSONObject());set(store,"motion",true);invoke("navigate",new Class[]{String.class},"home");
            ok(find(decor(),"最近13周游玩热力图")==null&&prefix(decor(),"选择专家难度")==null,"home hides detailed statistics and difficulty grid");
            for(String label:new String[]{"游戏中心","专注对局","统计","设置"}){ViewGroup item=(ViewGroup)find(decor(),label);ok(item!=null&&item.getChildCount()==1&&!(item.getChildAt(0) instanceof TextView),"four icon-only accessible navigation: "+label);}
            click("专注对局");ok(game()==null&&field(activity,"page").equals("setup"),"game tab with no game opens guide without starting");choose("不限错练习模式");ok((Integer)field(activity,"setupStep")==1&&(Boolean)field(activity,"relaxed"),"mode choice advances guide");choose("选择专家难度");ok(game()==null&&(Integer)field(activity,"chosenLevel")==3,"difficulty selection does not start a game");activity.onBackPressed();ok((Integer)field(activity,"setupStep")==0&&game()==null,"back preserves choices without starting");choose("不限错练习模式");ok(prefix(decor(),"选择专家难度").isSelected(),"chosen difficulty survives back");});
        final Bundle saved=new Bundle();ui(()->{callActivityOnSaveInstanceState(activity,saved);ok(saved.getInt("setupStep")==1&&saved.getInt("chosenLevel")==3&&saved.getBoolean("relaxed"),"guide state saved for recreation");});
        ActivityMonitor monitor=addMonitor("com.tankecho.zensudoku.MainActivity",null,false);ui(()->activity.recreate());Activity recreated=monitor.waitForActivityWithTimeout(5000);removeMonitor(monitor);ok(recreated!=null,"actual activity recreation completed");activity=recreated;SystemClock.sleep(400);
        ui(()->{ok(field(activity,"page").equals("setup")&&(Integer)field(activity,"setupStep")==1&&(Integer)field(activity,"chosenLevel")==3,"actual recreation restores step and difficulty");click("确认开始游戏");ok(game()!=null&&(Boolean)field(game(),"practice")&&integer("level")==3,"explicit start creates chosen practice");});
        final String[] original={null};ui(()->{original[0]=(String)field(game(),"id");click("游戏中心");click("开始新游戏");choose("三错挑战模式");choose("选择简单难度");ok(original[0].equals(field(game(),"id"))&&status().equals("playing"),"guide changes preserve running game");click("确认开始游戏");AlertDialog confirm=(AlertDialog)field(activity,"startConfirmationDialog");ok(confirm!=null&&confirm.isShowing()&&status().equals("playing"),"only explicit start requests abandon confirmation");confirm.getButton(AlertDialog.BUTTON_NEGATIVE).performClick();});SystemClock.sleep(150);
        ui(()->{ok(original[0].equals(field(game(),"id"))&&status().equals("playing")&&field(activity,"page").equals("game"),"cancel preserves old board and resumes it");click("游戏中心");click("开始新游戏");choose("三错挑战模式");choose("选择简单难度");click("确认开始游戏");((AlertDialog)field(activity,"startConfirmationDialog")).getButton(AlertDialog.BUTTON_POSITIVE).performClick();});SystemClock.sleep(150);
        ui(()->{ok(!original[0].equals(field(game(),"id"))&&!(Boolean)field(game(),"practice"),"confirm starts new challenge");JSONObject records=(JSONObject)field(field(activity,"store"),"records");ok(records.getJSONObject(original[0]).getString("status").equals("abandoned"),"abandoned old game recorded once");
            click("统计");ok(find(decor(),"最近13周游玩热力图")!=null&&find(decor(),"切换主题")==null,"heatmap in statistics with no settings mixed in");click("统计奖章");ok(count(decor(),"奖章 ")==16,"sixteen visible medal cards");choose("奖章 初次相遇");AlertDialog medal=(AlertDialog)field(activity,"medalDialog");ok(medal!=null&&medal.isShowing(),"locked medal opens readable requirement");medal.dismiss();
            click("设置");ok(find(decor(),"切换主题")!=null&&find(decor(),"导出存档")!=null&&find(decor(),"最近13周游玩热力图")==null,"settings dedicated to preferences and backup");ok(findText(decor(),activity.getPackageManager().getPackageInfo(activity.getPackageName(),0).versionName)!=null&&find(decor(),"项目 GitHub")!=null,"about has version and repository state");
            click("新局默认快速模式");ok((Boolean)field(field(activity,"store"),"quickMode"),"new default quick preference works");ok(!(Boolean)field(game(),"quickMode"),"default preference does not silently change active game");
            click("完成动效");invoke("navigate",new Class[]{String.class},"home");ok(((View)field(activity,"content")).getAlpha()==1&&((View)field(activity,"content")).getTranslationY()==0,"motion-off page transition remains still");
            seedRecords();set(field(activity,"store"),"motion",true);set(activity,"statsTab",1);invoke("navigate",new Class[]{String.class},"stats");ok(prefix(decor(),"奖章 初次相遇").getContentDescription().toString().contains("已获得"),"existing records retroactively unlock medal");choose("奖章 初次相遇");ok(((AlertDialog)field(activity,"medalDialog")).isShowing(),"earned medal detail opens");((AlertDialog)field(activity,"medalDialog")).dismiss();click("统计记录");ok(count(decor(),"对局记录 ")==20,"history initial page capped at twenty");click("加载更多记录");ok(count(decor(),"对局记录 ")==33&&find(decor(),"加载更多记录")==null,"history loads final page including current game");
            invoke("navigate",new Class[]{String.class},"profile");ok(field(activity,"page").equals("stats"),"legacy profile route maps to statistics");set(activity,"statsTab",0);invoke("changeTheme",new Class[]{int.class},1);ok(find(decor(),"最近13周游玩热力图")!=null,"dark statistics render");});
        final Object[] realGame={null};ui(()->{realGame[0]=game();region(4,true,true,0);place();int n=values("solution")[40];View key=find(decor(),"\u8f93\u5165\u6570\u5b57 "+n+"\uff0c\u5df2\u5b8c\u6210");float alpha=key.getAlpha();callActivityOnPause(activity);callActivityOnResume(activity);ok(!key.isEnabled()&&key.getAlpha()==alpha,"motion cleanup preserves disabled quick-key opacity");set(activity,"game",realGame[0]);invoke("navigate",new Class[]{String.class},"stats");invoke("changeTheme",new Class[]{int.class},1);});
        SystemClock.sleep(400);shot("stats-dark");ui(()->{invoke("changeTheme",new Class[]{int.class},0);click("游戏中心");});SystemClock.sleep(400);shot("home");ui(()->{click("设置");});SystemClock.sleep(400);shot("settings");
        ui(()->{Object store=field(activity,"store");String backup=(String)store.getClass().getMethod("exportBackup").invoke(store);JSONObject valid=(JSONObject)store.getClass().getMethod("validateBackup",String.class).invoke(null,backup);ok(valid.getJSONObject("records").length()==34,"new navigation and medals preserve backup format");activity.finish();});
        out.putString("stream",log+"PASS "+checks+" V19 navigation, statistics and settings device checks\n");finish(Activity.RESULT_OK,out);
    }catch(Throwable e){out.putString("stream",log+"FAIL "+android.util.Log.getStackTraceString(e));finish(Activity.RESULT_CANCELED,out);}}
}
